services:
  app: 
    build: .
    container_name: meu-app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/meubanco
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev

  postgres:
    image: postgres:17
    container_name: meu-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
